version: '3.7' # specify docker-compose version

# Define the services/containers to be run
services:
    laravel: # name of the first service
        build: ./ # specify the directory of the Dockerfile
        ports:
            - "8000:8000" # specify port forewarding
        volumes:
            - ./:/app
